# Generated by rust2rpm 10
%bcond_without check
%global debug_package %{nil}

%global crate ryu

Name:           rust-%{crate}
Version:        1.0.5
Release:        1
Summary:        Fast floating point to string conversion

# Upstream license specification: Apache-2.0 OR BSL-1.0
License:        ASL 2.0 or Boost
URL:            https://crates.io/crates/ryu
Source:         %{crates_source}
Patch0:		ryu-1.0.5-allow-newer-rand.patch

ExclusiveArch:  %{rust_arches}
%if %{__cargo_skip_build}
BuildArch:      noarch
%endif

BuildRequires:  rust-packaging

%global _description %{expand:
Fast floating point to string conversion.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages
which use "%{crate}" crate.

%files          devel
%license LICENSE-APACHE LICENSE-BOOST
%doc README.md
%{cargo_registry}/%{crate}-%{version}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages
which use "default" feature of "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+no-panic-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+no-panic-devel %{_description}

This package contains library source intended for building other packages
which use "no-panic" feature of "%{crate}" crate.

%files       -n %{name}+no-panic-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%package     -n %{name}+small-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+small-devel %{_description}

This package contains library source intended for building other packages
which use "small" feature of "%{crate}" crate.

%files       -n %{name}+small-devel
%ghost %{cargo_registry}/%{crate}-%{version}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version_no_tilde} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif
